/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeLog: typeof import('./theme/components/ChangeLog.md')['default']
    CleanupOutdatedCaches: typeof import('./theme/components/CleanupOutdatedCaches.md')['default']
    ExamplesBehaviors: typeof import('./theme/components/ExamplesBehaviors.md')['default']
    ExamplesGenerateSW: typeof import('./theme/components/ExamplesGenerateSW.md')['default']
    ExamplesInjectManifest: typeof import('./theme/components/ExamplesInjectManifest.md')['default']
    GenerateSWCleanupOutdatedCaches: typeof import('./theme/components/GenerateSWCleanupOutdatedCaches.md')['default']
    GenerateSWSourceMap: typeof import('./theme/components/GenerateSWSourceMap.md')['default']
    HeuristicWorkboxWindow: typeof import('./theme/components/HeuristicWorkboxWindow.md')['default']
    HomePage: typeof import('./theme/components/HomePage.vue')['default']
    InjectManifestBuild: typeof import('./theme/components/InjectManifestBuild.md')['default']
    InjectManifestCleanupOutdatedCaches: typeof import('./theme/components/InjectManifestCleanupOutdatedCaches.md')['default']
    InjectManifestSourceMap: typeof import('./theme/components/InjectManifestSourceMap.md')['default']
    NavBarTitle: typeof import('./theme/components/vp/NavBarTitle.vue')['default']
    PromptForUpdateImg: typeof import('./theme/components/PromptForUpdateImg.vue')['default']
    ReactReactiveWarning: typeof import('./theme/components/ReactReactiveWarning.md')['default']
    ReloadPrompt: typeof import('./theme/components/ReloadPrompt.vue')['default']
    RunExamples: typeof import('./theme/components/RunExamples.md')['default']
    ScaffoldingPWAProject: typeof import('./theme/components/ScaffoldingPWAProject.md')['default']
    ServiceWorkerClientErrors: typeof import('./theme/components/ServiceWorkerClientErrors.md')['default']
    SsrSsg: typeof import('./theme/components/SsrSsg.md')['default']
    TeamMembersItem: typeof import('./theme/components/vp/TeamMembersItem.vue')['default']
    TypeScriptError2307: typeof import('./theme/components/TypeScriptError2307.md')['default']
  }
}
